/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlydtdd;

import BUS.khachhangBUS;
import DTO.khachhangDTO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class QuanLyKhachHang extends javax.swing.JInternalFrame {

    /**
     * Creates new form QuanLyKhacHang
     */
    String [] columns = new String [] {"Mã khách hàng","Họ","Tên","Điện thoại","Địa chỉ"};
    DefaultTableModel modeltable = new DefaultTableModel(null, columns);
        
    void HienThiDS(ArrayList ds) 
    {
        modeltable.getDataVector().removeAllElements();
        for (int i = 0; i < ds.size(); i++) {
            khachhangDTO a = (khachhangDTO) ds.get(i);
            modeltable.insertRow(i, new Object[]{a.makh, a.ho, a.ten, a.sdt, a.diachi});
        }
        jTable1.setModel(modeltable);
    }
    
    public QuanLyKhachHang() {
        initComponents();
        ArrayList dskh = khachhangBUS.TimKiemTatCa();
        HienThiDS(dskh);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MaKHLabel = new javax.swing.JLabel();
        MaKHText = new javax.swing.JTextField();
        HoLabel = new javax.swing.JLabel();
        HoText = new javax.swing.JTextField();
        TenLabel = new javax.swing.JLabel();
        TenText = new javax.swing.JTextField();
        SDTLabel = new javax.swing.JLabel();
        SDTText = new javax.swing.JTextField();
        DiaChiLabel = new javax.swing.JLabel();
        DiaChiText = new javax.swing.JTextField();
        ThemButton = new javax.swing.JButton();
        SuaButton = new javax.swing.JButton();
        TuKhoaLabel = new javax.swing.JLabel();
        TuKhoaText = new javax.swing.JTextField();
        TimButton = new javax.swing.JButton();
        DanhSachButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        MaKHLabel.setText("Mã khách hàng:");

        MaKHText.setEditable(false);
        MaKHText.setEnabled(false);
        MaKHText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaKHTextActionPerformed(evt);
            }
        });

        HoLabel.setText("Họ:");

        HoText.setEnabled(false);
        HoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HoTextActionPerformed(evt);
            }
        });

        TenLabel.setText("Tên:");

        TenText.setEnabled(false);
        TenText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TenTextActionPerformed(evt);
            }
        });

        SDTLabel.setText("Số điện thoại:");

        SDTText.setEnabled(false);
        SDTText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SDTTextActionPerformed(evt);
            }
        });

        DiaChiLabel.setText("Địa chỉ:");

        DiaChiText.setEnabled(false);
        DiaChiText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiaChiTextActionPerformed(evt);
            }
        });

        ThemButton.setText("Thêm");
        ThemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemButtonActionPerformed(evt);
            }
        });

        SuaButton.setText("Sửa");
        SuaButton.setEnabled(false);
        SuaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuaButtonActionPerformed(evt);
            }
        });

        TuKhoaLabel.setText("Từ khóa:");

        TimButton.setText("Tìm");
        TimButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimButtonActionPerformed(evt);
            }
        });

        DanhSachButton.setText("Hiển thị danh sách");
        DanhSachButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DanhSachButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ThemButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SuaButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(TuKhoaLabel)
                .addGap(6, 6, 6)
                .addComponent(TuKhoaText, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TimButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DanhSachButton)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DiaChiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MaKHLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MaKHText, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HoText, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(SDTLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TenLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TenText, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SDTText, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(DiaChiText)))
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaKHLabel)
                    .addComponent(MaKHText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SDTLabel)
                    .addComponent(SDTText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TenLabel)
                        .addComponent(TenText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(HoLabel)
                        .addComponent(HoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DiaChiLabel)
                    .addComponent(DiaChiText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TuKhoaLabel)
                    .addComponent(TuKhoaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TimButton)
                    .addComponent(DanhSachButton)
                    .addComponent(ThemButton)
                    .addComponent(SuaButton))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {DiaChiLabel, DiaChiText, HoLabel, HoText, MaKHLabel, MaKHText, SDTLabel, SDTText, TenLabel, TenText});

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã khách hàng", "Họ", "Tên", "Điện thoại", "Địa chỉ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(70);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(120);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MaKHTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaKHTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaKHTextActionPerformed

    private void TenTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TenTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TenTextActionPerformed

    private void HoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HoTextActionPerformed

    private void SDTTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SDTTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SDTTextActionPerformed

    private void DiaChiTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiaChiTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DiaChiTextActionPerformed

    private void SuaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuaButtonActionPerformed
        if(MaKHText.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập mã khách hàng!!!!","Missing information",JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(TenText.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập tên khách hàng!!!!","Missing information",JOptionPane.ERROR_MESSAGE);
            return;
        }
        khachhangDTO kh = new khachhangDTO();
        kh.makh = MaKHText.getText();
        kh.ho = HoText.getText();
        kh.ten = TenText.getText();
        kh.sdt = SDTText.getText();
        kh.diachi = DiaChiText.getText();
        khachhangBUS.Sua(kh);
        JOptionPane.showMessageDialog(null, "Sửa thành công","Success",JOptionPane.INFORMATION_MESSAGE);
        ArrayList dskh = khachhangBUS.TimKiemTatCa();
        HienThiDS(dskh);
    }//GEN-LAST:event_SuaButtonActionPerformed

    private void ThemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemButtonActionPerformed
        ThemKhachHang a = new ThemKhachHang();
        a.setLocationRelativeTo(null);
        a.setVisible(true);
        a.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        //Refresh jTable
        a.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent windowEvent) {
                ArrayList dskh = khachhangBUS.TimKiemTatCa();
                HienThiDS(dskh);
            }
        });
    }//GEN-LAST:event_ThemButtonActionPerformed

    private void TimButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimButtonActionPerformed
        String tukhoa = TuKhoaText.getText();
        ArrayList dskh = khachhangBUS.TimKiemTheoTuKhoa(tukhoa);
        HienThiDS(dskh);
        if(dskh.isEmpty()){
            JOptionPane.showMessageDialog(null, "Không tìm thấy kết quả!!!","Not found",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_TimButtonActionPerformed

    private void DanhSachButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DanhSachButtonActionPerformed
        ArrayList dskh = khachhangBUS.TimKiemTatCa();
        HienThiDS(dskh);
    }//GEN-LAST:event_DanhSachButtonActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        String makh = (String) modeltable.getValueAt(jTable1.getSelectedRow(), 0);
        String ho = (String) modeltable.getValueAt(jTable1.getSelectedRow(), 1);
        String ten = (String) modeltable.getValueAt(jTable1.getSelectedRow(), 2);
        String sdt = (String) modeltable.getValueAt(jTable1.getSelectedRow(), 3);
        String diachi = (String) modeltable.getValueAt(jTable1.getSelectedRow(), 4);
        MaKHText.setText(makh);
        HoText.setText(ho);
        TenText.setText(ten);
        SDTText.setText(sdt);
        DiaChiText.setText(diachi);
        MaKHText.enable();
        HoText.enable();
        TenText.enable();
        SDTText.enable();
        DiaChiText.enable();
        SuaButton.setEnabled(true);
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DanhSachButton;
    private javax.swing.JLabel DiaChiLabel;
    private javax.swing.JTextField DiaChiText;
    private javax.swing.JLabel HoLabel;
    private javax.swing.JTextField HoText;
    private javax.swing.JLabel MaKHLabel;
    private javax.swing.JTextField MaKHText;
    private javax.swing.JLabel SDTLabel;
    private javax.swing.JTextField SDTText;
    private javax.swing.JButton SuaButton;
    private javax.swing.JLabel TenLabel;
    private javax.swing.JTextField TenText;
    private javax.swing.JButton ThemButton;
    private javax.swing.JButton TimButton;
    private javax.swing.JLabel TuKhoaLabel;
    private javax.swing.JTextField TuKhoaText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
