/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlydtdd;

import DTO.sanphamDTO;
import DTO.loaisanphamDTO;
import DTO.nhacungcapDTO;
import BUS.sanphamBUS;
import BUS.loaisanphamBUS;
import BUS.nhacungcapBUS;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import static java.nio.file.StandardCopyOption.REPLACE_EXISTING;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class QuanLyThongTinSanPham extends javax.swing.JInternalFrame {

    /**
     * Creates new form QuanLyThongTinSanPham
     */
    String [] columns = new String [] {"Mã nhân viên","Tên","Loại","Nhà cung cấp","Hình ảnh","Số lượng","Giá"};
    DefaultTableModel modeltable = new DefaultTableModel(null, columns);
    DefaultComboBoxModel modelcombobox1 = new DefaultComboBoxModel();
    DefaultComboBoxModel modelcombobox2 = new DefaultComboBoxModel();
    JFileChooser jfc;
    String imageurl;
    
    void HienThiLoaiSP(ArrayList dsl)
    {
        for (int i = 0; i< dsl.size(); i++) {
            loaisanphamDTO a = (loaisanphamDTO) dsl.get(i);
            modelcombobox1.addElement(a.tenloai);
        }
        LoaiComboBox.setModel(modelcombobox1);
    }
    
    void HienThiNCC(ArrayList dsncc)
    {
        for (int i = 0; i< dsncc.size(); i++) {
            nhacungcapDTO a = (nhacungcapDTO) dsncc.get(i);
            modelcombobox2.addElement(a.tenncc);
        }
        NCCComboBox.setModel(modelcombobox2);
    }
    
    void HienThiDS(ArrayList dssp) 
    {
        modeltable.getDataVector().removeAllElements();
        for (int i = 0; i < dssp.size(); i++) {
            sanphamDTO a = (sanphamDTO) dssp.get(i);
            ArrayList dsl = loaisanphamBUS.TimKiemTheoTuKhoa(a.maloai);
            loaisanphamDTO b = (loaisanphamDTO) dsl.get(0);
            ArrayList dsncc = nhacungcapBUS.TimKiemTheoTuKhoa(a.mancc);
            nhacungcapDTO c = (nhacungcapDTO) dsncc.get(0);
            modeltable.insertRow(i, new Object[]{a.masp, a.tensp, b.tenloai, c.tenncc, a.hinhanh, a.soluong, String.format("%.0f", a.gia)});
        }
        jTable1.setModel(modeltable);
    }
    
    public QuanLyThongTinSanPham() {
        initComponents();
        TenAnhLabel.setText("No file selected");
        ImageIcon image = new ImageIcon(this.getClass().getResource("/images/No_image_available.png"));
        //Resize image
        Image newimage = image.getImage();
        Image resize = newimage.getScaledInstance(150, 158, java.awt.Image.SCALE_SMOOTH);
        image = new ImageIcon(resize);
        //Show image
        HinhAnhLabel.setIcon(image);
        ArrayList dsl = loaisanphamBUS.TimKiemTatCa();
        HienThiLoaiSP(dsl);
        ArrayList dsncc = nhacungcapBUS.TimKiemTatCa();
        HienThiNCC(dsncc);
        ArrayList dssp = sanphamBUS.TimKiemTatCa();
        HienThiDS(dssp);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MaSPLabel = new javax.swing.JLabel();
        MaSPText = new javax.swing.JTextField();
        TenLabel = new javax.swing.JLabel();
        TenText = new javax.swing.JTextField();
        GIaLabel = new javax.swing.JLabel();
        GiaText = new javax.swing.JTextField();
        SoLuongLabel = new javax.swing.JLabel();
        SoLuongText = new javax.swing.JTextField();
        LoaiLabel = new javax.swing.JLabel();
        LoaiComboBox = new javax.swing.JComboBox<>();
        NCCLabel = new javax.swing.JLabel();
        ThemButton = new javax.swing.JButton();
        SuaButton = new javax.swing.JButton();
        XoaButton = new javax.swing.JButton();
        NCCComboBox = new javax.swing.JComboBox<>();
        HinhAnhLabel = new javax.swing.JLabel();
        TuKhoaLabel = new javax.swing.JLabel();
        TuKhoaText = new javax.swing.JTextField();
        TimButton = new javax.swing.JButton();
        DanhSachButton = new javax.swing.JButton();
        HinhAnhButton = new javax.swing.JButton();
        TenAnhLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        MaSPLabel.setText("Mã sp:");

        MaSPText.setEditable(false);
        MaSPText.setEnabled(false);
        MaSPText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaSPTextActionPerformed(evt);
            }
        });

        TenLabel.setText("Tên sp:");

        TenText.setEnabled(false);
        TenText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TenTextActionPerformed(evt);
            }
        });

        GIaLabel.setText("Đơn giá:");

        GiaText.setEnabled(false);
        GiaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GiaTextActionPerformed(evt);
            }
        });

        SoLuongLabel.setText("Số lượng:");

        SoLuongText.setEditable(false);
        SoLuongText.setEnabled(false);
        SoLuongText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoLuongTextActionPerformed(evt);
            }
        });

        LoaiLabel.setText("Loại:");

        LoaiComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        LoaiComboBox.setEnabled(false);

        NCCLabel.setText("Nhà cung cấp:");

        ThemButton.setText("Thêm");
        ThemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemButtonActionPerformed(evt);
            }
        });

        SuaButton.setText("Sửa");
        SuaButton.setEnabled(false);
        SuaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuaButtonActionPerformed(evt);
            }
        });

        XoaButton.setText("Xóa");
        XoaButton.setEnabled(false);
        XoaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XoaButtonActionPerformed(evt);
            }
        });

        NCCComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        NCCComboBox.setEnabled(false);

        TuKhoaLabel.setText("Từ khóa:");

        TimButton.setText("Tìm");
        TimButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimButtonActionPerformed(evt);
            }
        });

        DanhSachButton.setText("Hiển thị danh sách");
        DanhSachButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DanhSachButtonActionPerformed(evt);
            }
        });

        HinhAnhButton.setText("Choose file");
        HinhAnhButton.setEnabled(false);
        HinhAnhButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HinhAnhButtonActionPerformed(evt);
            }
        });

        TenAnhLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TenAnhLabel.setText(" No file selected");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(NCCLabel)
                                .addGap(18, 18, 18)
                                .addComponent(NCCComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TenLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(MaSPLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(LoaiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(GIaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                                    .addComponent(SoLuongLabel))
                                .addGap(42, 42, 42)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MaSPText, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TenText, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(GiaText, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LoaiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SoLuongText, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TenAnhLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(HinhAnhButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(HinhAnhLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ThemButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SuaButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(XoaButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(TuKhoaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TuKhoaText, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TimButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DanhSachButton)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(MaSPLabel)
                        .addGap(18, 18, 18)
                        .addComponent(TenLabel)
                        .addGap(18, 18, 18)
                        .addComponent(GIaLabel)
                        .addGap(18, 18, 18)
                        .addComponent(SoLuongLabel)
                        .addGap(18, 18, 18)
                        .addComponent(LoaiLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(MaSPText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TenText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(GiaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SoLuongText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(HinhAnhLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HinhAnhButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LoaiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NCCLabel)
                            .addComponent(NCCComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(TenAnhLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ThemButton)
                    .addComponent(SuaButton)
                    .addComponent(XoaButton)
                    .addComponent(TuKhoaLabel)
                    .addComponent(TuKhoaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TimButton)
                    .addComponent(DanhSachButton))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {GIaLabel, GiaText, LoaiComboBox, LoaiLabel, MaSPLabel, MaSPText, NCCLabel, SoLuongLabel, SoLuongText, TenLabel, TenText});

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên", "Loại", "Nhà cung cấp", "Hình ảnh", "Số lượng", "Giá"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MaSPTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaSPTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaSPTextActionPerformed

    private void SoLuongTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoLuongTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SoLuongTextActionPerformed

    private void GiaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GiaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GiaTextActionPerformed

    private void TenTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TenTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TenTextActionPerformed

    private void SuaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuaButtonActionPerformed
        if(MaSPText.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập mã sản phẩm!!!!","Missing information",JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(TenText.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập tên sản phẩm!!!!","Missing information",JOptionPane.ERROR_MESSAGE);
            return;
        }
        sanphamDTO sp = new sanphamDTO();
        sp.masp = MaSPText.getText();
        sp.tensp = TenText.getText();
        sp.gia = Float.valueOf(GiaText.getText());
        sp.soluong = Integer.valueOf(SoLuongText.getText());
        String loai = LoaiComboBox.getSelectedItem().toString();
        ArrayList dsl = loaisanphamBUS.TimKiemTheoTuKhoa(loai);
        loaisanphamDTO b = (loaisanphamDTO) dsl.get(0);
        sp.maloai = b.maloai;
        String ncc = NCCComboBox.getSelectedItem().toString();
        ArrayList dsncc = nhacungcapBUS.TimKiemTheoTen(ncc);
        nhacungcapDTO c = (nhacungcapDTO) dsncc.get(0);
        sp.mancc = c.mancc;
        String tenanh = TenAnhLabel.getText();
        if(tenanh.equals("No file selected"))
            sp.hinhanh = "";
        else{
            sp.hinhanh = tenanh.substring(0, tenanh.lastIndexOf(".jpg"));
            //Copy image to this project folder
            if(jfc != null)
            {
                try{
                    String projectpath = System.getProperty("user.dir");
                    projectpath = projectpath + "\\src\\images\\"+jfc.getSelectedFile().getName();
                    projectpath = projectpath.replace("\\", File.separator);
                    Path src = Paths.get(jfc.getSelectedFile().getAbsolutePath());
                    Path dest = Paths.get(projectpath);
                    Files.copy(src, dest, REPLACE_EXISTING);
                }catch(IOException e){
                    e.printStackTrace();
                }
            }
        }
        sanphamBUS.Sua(sp);
        JOptionPane.showMessageDialog(null, "Sửa thành công","Success",JOptionPane.INFORMATION_MESSAGE);
        ArrayList dssp = sanphamBUS.TimKiemTatCa();
        HienThiDS(dssp);
    }//GEN-LAST:event_SuaButtonActionPerformed

    private void ThemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemButtonActionPerformed
        ThemSanPham a = new ThemSanPham();
        a.setLocationRelativeTo(null);
        a.setVisible(true);
        a.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        //Refresh jTable
        a.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent windowEvent) {
                ArrayList dssp = sanphamBUS.TimKiemTatCa();
                HienThiDS(dssp);
            }
        });
    }//GEN-LAST:event_ThemButtonActionPerformed

    private void XoaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XoaButtonActionPerformed
        String s = MaSPText.getText();
        int dialogResult = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xóa?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
        if(dialogResult == JOptionPane.YES_OPTION)
        {
            sanphamBUS.Xoa(s);
            JOptionPane.showMessageDialog(null, "Xóa thành công","Success",JOptionPane.INFORMATION_MESSAGE);
            ArrayList dssp = sanphamBUS.TimKiemTatCa();
            HienThiDS(dssp);
            MaSPText.setText("");
            TenText.setText("");
            GiaText.setText("");
            SoLuongText.setText("");
            TenAnhLabel.setText("No file selected");
            ImageIcon image = new ImageIcon(this.getClass().getResource("/images/No_image_available.png"));
            //Resize image
            Image newimage = image.getImage();
            Image resize = newimage.getScaledInstance(150, 158, java.awt.Image.SCALE_SMOOTH);
            image = new ImageIcon(resize);
            //Show image
            HinhAnhLabel.setIcon(image);
            MaSPText.enable(false);
            TenText.enable(false);
            GiaText.enable(false);
            SoLuongText.enable(false);
            LoaiComboBox.setEnabled(false);
            NCCComboBox.setEnabled(false);
            HinhAnhButton.setEnabled(false);
            SuaButton.setEnabled(false);
            XoaButton.setEnabled(false);
        }
    }//GEN-LAST:event_XoaButtonActionPerformed

    private void TimButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimButtonActionPerformed
        String tukhoa = TuKhoaText.getText();
        ArrayList dssp = sanphamBUS.TimKiemTheoTuKhoa(tukhoa);
        HienThiDS(dssp);
        if(dssp.isEmpty()){
            JOptionPane.showMessageDialog(null, "Không tìm thấy kết quả!!!","Not found",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_TimButtonActionPerformed

    private void DanhSachButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DanhSachButtonActionPerformed
        ArrayList dssp = sanphamBUS.TimKiemTatCa();
        HienThiDS(dssp);
    }//GEN-LAST:event_DanhSachButtonActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        String masp = (String) modeltable.getValueAt(jTable1.getSelectedRow(), 0);
        String tensp = (String) modeltable.getValueAt(jTable1.getSelectedRow(), 1);
        String loai = (String) modeltable.getValueAt(jTable1.getSelectedRow(), 2);
        String ncc = (String) modeltable.getValueAt(jTable1.getSelectedRow(), 3);
        String hinhanh = (String) modeltable.getValueAt(jTable1.getSelectedRow(), 4);
        int soluong = (int) modeltable.getValueAt(jTable1.getSelectedRow(), 5);
        String gia = (String) modeltable.getValueAt(jTable1.getSelectedRow(), 6);
        MaSPText.setText(masp);
        TenText.setText(tensp);
        SoLuongText.setText(String.valueOf(soluong));
        GiaText.setText(gia);
        for (int i = 0; i< LoaiComboBox.getItemCount(); i++) {
            if(loai.equals(LoaiComboBox.getItemAt(i)))
                LoaiComboBox.setSelectedIndex(i);
        }
        for (int i = 0; i< NCCComboBox.getItemCount(); i++) {
            if(ncc.equals(NCCComboBox.getItemAt(i)))
                NCCComboBox.setSelectedIndex(i);
        }
        String imageurl = "/images/"+hinhanh+".jpg";
        ImageIcon image = new ImageIcon(getClass().getResource(imageurl));
        //Resize image
        Image newimage = image.getImage();
        Image resize = newimage.getScaledInstance(150, 158, java.awt.Image.SCALE_SMOOTH);
        image = new ImageIcon(resize);
        //Show image
        if (image != null) {
            HinhAnhLabel.setIcon(image);
            TenAnhLabel.setText(hinhanh+".jpg");
        } else {
            HinhAnhLabel.setIcon(new ImageIcon(this.getClass().getResource("/images/No_image_available.png")));
        }
        MaSPText.enable();
        TenText.enable();
        GiaText.enable();
        SoLuongText.enable();
        LoaiComboBox.setEnabled(true);
        NCCComboBox.setEnabled(true);
        HinhAnhButton.setEnabled(true);
        SuaButton.setEnabled(true);
        XoaButton.setEnabled(true);
    }//GEN-LAST:event_jTable1MouseClicked

    private void HinhAnhButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HinhAnhButtonActionPerformed
        jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        FileNameExtensionFilter filter = new FileNameExtensionFilter("IMAGE FILES (.jpg)", "jpg", "JPG Images");
        jfc.setFileFilter(filter);
        jfc.setAcceptAllFileFilterUsed(false);
        int returnValue = jfc.showOpenDialog(null);
        if(returnValue == JFileChooser.APPROVE_OPTION)
        {
            File selectedFile = jfc.getSelectedFile();
            String imgname = selectedFile.getName();
            TenAnhLabel.setText(imgname);
            imageurl = selectedFile.getAbsolutePath();
            ImageIcon image = new ImageIcon(imageurl);
            //If image is not available
            if (image != null) {
            } else {
                image = new ImageIcon(this.getClass().getResource("/images/No_image_available.png"));
            }
            //Resize image
            Image newimage = image.getImage();
            Image resize = newimage.getScaledInstance(150, 158, java.awt.Image.SCALE_SMOOTH);
            image = new ImageIcon(resize);
            //Show image
            HinhAnhLabel.setIcon(image);
        }
    }//GEN-LAST:event_HinhAnhButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DanhSachButton;
    private javax.swing.JLabel GIaLabel;
    private javax.swing.JTextField GiaText;
    private javax.swing.JButton HinhAnhButton;
    private javax.swing.JLabel HinhAnhLabel;
    private javax.swing.JComboBox<String> LoaiComboBox;
    private javax.swing.JLabel LoaiLabel;
    private javax.swing.JLabel MaSPLabel;
    private javax.swing.JTextField MaSPText;
    private javax.swing.JComboBox<String> NCCComboBox;
    private javax.swing.JLabel NCCLabel;
    private javax.swing.JLabel SoLuongLabel;
    private javax.swing.JTextField SoLuongText;
    private javax.swing.JButton SuaButton;
    private javax.swing.JLabel TenAnhLabel;
    private javax.swing.JLabel TenLabel;
    private javax.swing.JTextField TenText;
    private javax.swing.JButton ThemButton;
    private javax.swing.JButton TimButton;
    private javax.swing.JLabel TuKhoaLabel;
    private javax.swing.JTextField TuKhoaText;
    private javax.swing.JButton XoaButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
