/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlydtdd;

import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author ASUS
 */
public class QuanLyHoaDon extends javax.swing.JInternalFrame {

    /**
     * Creates new form QuanLyNhanVien
     */
    private void QLHDXuat()
    {
        QuanLyHoaDonXuat qlhdx = new QuanLyHoaDonXuat();
        /*Remove title bar*/
        BasicInternalFrameUI bqlhdx = (BasicInternalFrameUI)qlhdx.getUI();
        bqlhdx.setNorthPane(null);
        //Remove surrounding borders
        qlhdx.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        qlhdx.setSize(jDesktopPane1.getWidth(), jDesktopPane1.getHeight());
        //Show jInternalFrame
        jDesktopPane1.add(qlhdx);
        qlhdx.setVisible(true);
        try {
            qlhdx.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(QuanLyHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void QLHDNhap()
    {
        QuanLyHoaDonNhap qlhdn = new QuanLyHoaDonNhap();
        /*Remove title bar*/
        BasicInternalFrameUI bqlhdn = (BasicInternalFrameUI)qlhdn.getUI();
        bqlhdn.setNorthPane(null);
        //Remove surrounding borders
        qlhdn.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        qlhdn.setSize(jDesktopPane1.getWidth(), jDesktopPane1.getHeight());
        //Show jInternalFrame
        jDesktopPane1.add(qlhdn);
        qlhdn.setVisible(true);
        try {
            qlhdn.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(QuanLyHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public QuanLyHoaDon() {
        initComponents();
        ButtonGroup btg = new ButtonGroup();
        btg.add(QLHDNhap);
        btg.add(QLHDXuat);
        btg.setSelected(QLHDXuat.getModel(),true);
        QLHDXuat();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        QLHDXuat = new javax.swing.JToggleButton();
        QLHDNhap = new javax.swing.JToggleButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        QLHDXuat.setText("QUẢN LÝ  HÓA ĐƠN XUÂT");
        QLHDXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QLHDXuatActionPerformed(evt);
            }
        });

        QLHDNhap.setText("QUẢN LÝ HÓA ĐƠN NHẬP");
        QLHDNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QLHDNhapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(QLHDXuat, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QLHDNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(QLHDXuat, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addComponent(QLHDNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 497, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void QLHDXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QLHDXuatActionPerformed
        QLHDXuat();
    }//GEN-LAST:event_QLHDXuatActionPerformed

    private void QLHDNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QLHDNhapActionPerformed
        QLHDNhap();
    }//GEN-LAST:event_QLHDNhapActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton QLHDNhap;
    private javax.swing.JToggleButton QLHDXuat;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
