/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlydtdd;

import BUS.loaisanphamBUS;
import DTO.loaisanphamDTO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class QuanLyLoaiSP extends javax.swing.JInternalFrame {

    /**
     * Creates new form QuanLyLoaiSP
     */
    String [] columns = new String [] {"Mã loại","Tên"};
    DefaultTableModel modeltable = new DefaultTableModel(null, columns);
    
    void HienThiDS(ArrayList ds) 
    {
        modeltable.getDataVector().removeAllElements();
        for (int i = 0; i < ds.size(); i++) {
            loaisanphamDTO a = (loaisanphamDTO) ds.get(i);
            modeltable.insertRow(i, new Object[]{a.maloai, a.tenloai});
        }
        jTable1.setModel(modeltable);
    }
    
    public QuanLyLoaiSP() {
        initComponents();
        ArrayList dsl = loaisanphamBUS.TimKiemTatCa();
        HienThiDS(dsl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MaLoaiLabel = new javax.swing.JLabel();
        MaLoaiText = new javax.swing.JTextField();
        TenLabel = new javax.swing.JLabel();
        TenText = new javax.swing.JTextField();
        ThemButton = new javax.swing.JButton();
        SuaButton = new javax.swing.JButton();
        XoaButton = new javax.swing.JButton();
        TuKhoaLabel = new javax.swing.JLabel();
        TuKhoaText = new javax.swing.JTextField();
        TimButton = new javax.swing.JButton();
        DanhSachButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        MaLoaiLabel.setText("Mã loại:");

        MaLoaiText.setEditable(false);
        MaLoaiText.setEnabled(false);
        MaLoaiText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaLoaiTextActionPerformed(evt);
            }
        });

        TenLabel.setText("Tên:");

        TenText.setEnabled(false);
        TenText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TenTextActionPerformed(evt);
            }
        });

        ThemButton.setText("Thêm");
        ThemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemButtonActionPerformed(evt);
            }
        });

        SuaButton.setText("Sửa");
        SuaButton.setEnabled(false);
        SuaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuaButtonActionPerformed(evt);
            }
        });

        XoaButton.setText("Xóa");
        XoaButton.setEnabled(false);
        XoaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XoaButtonActionPerformed(evt);
            }
        });

        TuKhoaLabel.setText("Từ khóa:");

        TimButton.setText("Tìm");
        TimButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimButtonActionPerformed(evt);
            }
        });

        DanhSachButton.setText("Hiển thị danh sách");
        DanhSachButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DanhSachButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(MaLoaiLabel)
                .addGap(18, 18, 18)
                .addComponent(MaLoaiText, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TenText, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ThemButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SuaButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(XoaButton)
                .addGap(50, 50, 50)
                .addComponent(TuKhoaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TuKhoaText, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TimButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DanhSachButton)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaLoaiLabel)
                    .addComponent(MaLoaiText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TenLabel)
                    .addComponent(TenText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ThemButton)
                    .addComponent(SuaButton)
                    .addComponent(XoaButton)
                    .addComponent(TuKhoaLabel)
                    .addComponent(TuKhoaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TimButton)
                    .addComponent(DanhSachButton))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {MaLoaiLabel, MaLoaiText, TenLabel, TenText});

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã loại", "Tên"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MaLoaiTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaLoaiTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaLoaiTextActionPerformed

    private void TenTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TenTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TenTextActionPerformed

    private void SuaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuaButtonActionPerformed
        if(MaLoaiText.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập mã loại sản phẩm!!!!","Missing information",JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(TenText.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập tên loại sản phẩm!!!!","Missing information",JOptionPane.ERROR_MESSAGE);
            return;
        }
        loaisanphamDTO l = new loaisanphamDTO();
        l.maloai = MaLoaiText.getText();
        l.tenloai = TenText.getText();
        loaisanphamBUS.Sua(l);
        JOptionPane.showMessageDialog(null, "Sửa thành công","Success",JOptionPane.INFORMATION_MESSAGE);
        ArrayList dsl = loaisanphamBUS.TimKiemTatCa();
        HienThiDS(dsl);
    }//GEN-LAST:event_SuaButtonActionPerformed

    private void ThemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemButtonActionPerformed
        ThemLoaiSP a = new ThemLoaiSP();
        a.setLocationRelativeTo(null);
        a.setVisible(true);
        a.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        //Refresh jTable
        a.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent windowEvent) {
                ArrayList dsl = loaisanphamBUS.TimKiemTatCa();
                HienThiDS(dsl);
            }
        });
    }//GEN-LAST:event_ThemButtonActionPerformed

    private void XoaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XoaButtonActionPerformed
        String s = MaLoaiText.getText();
        int dialogResult = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xóa?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
        if(dialogResult == JOptionPane.YES_OPTION)
        {
            loaisanphamBUS.Xoa(s);
            JOptionPane.showMessageDialog(null, "Xóa thành công","Success",JOptionPane.INFORMATION_MESSAGE);
            ArrayList dsl = loaisanphamBUS.TimKiemTatCa();
            HienThiDS(dsl);
            MaLoaiText.setText("");
            TenText.setText("");
            MaLoaiText.enable(false);
            TenText.enable(false);
            SuaButton.setEnabled(false);
            XoaButton.setEnabled(false);
        }
    }//GEN-LAST:event_XoaButtonActionPerformed

    private void TimButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimButtonActionPerformed
        String tukhoa = TuKhoaText.getText();
        ArrayList dsl = loaisanphamBUS.TimKiemTheoTuKhoa(tukhoa);
        HienThiDS(dsl);
        if(dsl.isEmpty()){
            JOptionPane.showMessageDialog(null, "Không tìm thấy kết quả!!!","Not found",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_TimButtonActionPerformed

    private void DanhSachButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DanhSachButtonActionPerformed
        ArrayList dsl = loaisanphamBUS.TimKiemTatCa();
        HienThiDS(dsl);
    }//GEN-LAST:event_DanhSachButtonActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        String maloai = (String) modeltable.getValueAt(jTable1.getSelectedRow(), 0);
        String ten = (String) modeltable.getValueAt(jTable1.getSelectedRow(), 1);
        MaLoaiText.setText(maloai);
        TenText.setText(ten);
        MaLoaiText.enable();
        TenText.enable();
        SuaButton.setEnabled(true);
        XoaButton.setEnabled(true);
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DanhSachButton;
    private javax.swing.JLabel MaLoaiLabel;
    private javax.swing.JTextField MaLoaiText;
    private javax.swing.JButton SuaButton;
    private javax.swing.JLabel TenLabel;
    private javax.swing.JTextField TenText;
    private javax.swing.JButton ThemButton;
    private javax.swing.JButton TimButton;
    private javax.swing.JLabel TuKhoaLabel;
    private javax.swing.JTextField TuKhoaText;
    private javax.swing.JButton XoaButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
