/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlydtdd;

import BUS.loaisanphamBUS;
import BUS.nhacungcapBUS;
import BUS.sanphamBUS;
import DTO.loaisanphamDTO;
import DTO.nhacungcapDTO;
import DTO.sanphamDTO;
import java.awt.Component;
import java.awt.Image;
import java.io.File;
import java.io.FileFilter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import static java.nio.file.StandardCopyOption.REPLACE_EXISTING;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;

/**
 *
 * @author ASUS
 */
public class ThemSanPham extends javax.swing.JFrame {

    /**
     * Creates new form ThemSanPham
     */
    DefaultComboBoxModel modelcombobox1 = new DefaultComboBoxModel();
    DefaultComboBoxModel modelcombobox2 = new DefaultComboBoxModel();
    JFileChooser jfc;
    String imageurl;
    
    void HienThiLoaiSanPham(ArrayList dsl)
    {
        for (int i = 0; i< dsl.size(); i++) {
            loaisanphamDTO a = (loaisanphamDTO) dsl.get(i);
            modelcombobox1.addElement(a.tenloai);
        }
        LoaiComboBox.setModel(modelcombobox1);
    }
    
    void HienThiNCC(ArrayList dsncc)
    {
        for (int i = 0; i< dsncc.size(); i++) {
            nhacungcapDTO a = (nhacungcapDTO) dsncc.get(i);
            modelcombobox2.addElement(a.tenncc);
        }
        NCCComboBox.setModel(modelcombobox2);
    }
    
    public ThemSanPham() {
        initComponents();
        TenAnhLabel.setText("No file selected");
        ImageIcon image = new ImageIcon(this.getClass().getResource("/images/No_image_available.png"));
        //Resize image
        Image newimage = image.getImage();
        Image resize = newimage.getScaledInstance(150, 158, java.awt.Image.SCALE_SMOOTH);
        image = new ImageIcon(resize);
        //Show image
        HinhAnhLabel.setIcon(image);
        ArrayList dsl = loaisanphamBUS.TimKiemTatCa();
        HienThiLoaiSanPham(dsl);
        ArrayList dsncc = nhacungcapBUS.TimKiemTatCa();
        HienThiNCC(dsncc);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ThemButton = new javax.swing.JButton();
        HuyButton = new javax.swing.JButton();
        MaSPText = new javax.swing.JTextField();
        MaSPLabel = new javax.swing.JLabel();
        TenLabel = new javax.swing.JLabel();
        TenText = new javax.swing.JTextField();
        GIaLabel = new javax.swing.JLabel();
        GiaText = new javax.swing.JTextField();
        SoLuongLabel = new javax.swing.JLabel();
        SoLuongText = new javax.swing.JTextField();
        LoaiLabel = new javax.swing.JLabel();
        LoaiComboBox = new javax.swing.JComboBox<>();
        NCCLabel = new javax.swing.JLabel();
        NCCComboBox = new javax.swing.JComboBox<>();
        HinhAnhLabel = new javax.swing.JLabel();
        HinhAnhButton = new javax.swing.JButton();
        TenAnhLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thêm sản phẩm");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(34, 181, 115));
        jLabel1.setText("THÊM SẢN PHẨM");

        ThemButton.setText("Lưu");
        ThemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemButtonActionPerformed(evt);
            }
        });

        HuyButton.setText("Hủy");
        HuyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HuyButtonActionPerformed(evt);
            }
        });

        MaSPText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaSPTextActionPerformed(evt);
            }
        });

        MaSPLabel.setText("Mã sp:");

        TenLabel.setText("Tên sp:");

        TenText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TenTextActionPerformed(evt);
            }
        });

        GIaLabel.setText("Đơn giá:");

        GiaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GiaTextActionPerformed(evt);
            }
        });

        SoLuongLabel.setText("Số lượng:");

        SoLuongText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoLuongTextActionPerformed(evt);
            }
        });

        LoaiLabel.setText("Loại:");

        LoaiComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        NCCLabel.setText("Nhà cung cấp:");

        NCCComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        NCCComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NCCComboBoxActionPerformed(evt);
            }
        });

        HinhAnhButton.setText("Choose file");
        HinhAnhButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HinhAnhButtonActionPerformed(evt);
            }
        });

        TenAnhLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TenAnhLabel.setText(" No file selected");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(ThemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(HuyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MaSPLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GIaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SoLuongLabel)
                    .addComponent(LoaiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NCCLabel))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LoaiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SoLuongText, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(GiaText, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TenText, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MaSPText, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(HinhAnhLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NCCComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(149, 149, 149))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(335, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(TenAnhLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(48, 48, 48)
                            .addComponent(HinhAnhButton)))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MaSPLabel)
                            .addComponent(MaSPText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TenLabel)
                            .addComponent(TenText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GIaLabel)
                            .addComponent(GiaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SoLuongLabel)
                            .addComponent(SoLuongText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(HinhAnhLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoaiLabel)
                    .addComponent(LoaiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NCCLabel)
                    .addComponent(NCCComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ThemButton)
                    .addComponent(HuyButton))
                .addGap(23, 23, 23))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(240, 240, 240)
                    .addComponent(HinhAnhButton)
                    .addGap(6, 6, 6)
                    .addComponent(TenAnhLabel)
                    .addContainerGap(106, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HuyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HuyButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_HuyButtonActionPerformed

    private void ThemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemButtonActionPerformed
        if(MaSPText.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập mã sản phẩm!!!!","Missing information",JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(TenText.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập tên sản phẩm!!!!","Missing information",JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (sanphamBUS.kiemTraTonTai(MaSPText.getText()) == true)
        {
            JOptionPane.showConfirmDialog((Component) null, "Mã sản phẩm đã tồn tại", "alert", JOptionPane.CLOSED_OPTION);
            return;
        }
        sanphamDTO sp = new sanphamDTO();
        sp.masp = MaSPText.getText();
        sp.tensp = TenText.getText();
        sp.gia = Float.valueOf(GiaText.getText());
        sp.soluong = Integer.valueOf(SoLuongText.getText());
        String loai = LoaiComboBox.getSelectedItem().toString();
        ArrayList dsl = loaisanphamBUS.TimKiemTheoTuKhoa(loai);
        loaisanphamDTO a = (loaisanphamDTO) dsl.get(0);
        sp.maloai = a.maloai;
        String ncc = NCCComboBox.getSelectedItem().toString();
        ArrayList dsncc = nhacungcapBUS.TimKiemTheoTen(ncc);
        nhacungcapDTO b = (nhacungcapDTO) dsncc.get(0);
        sp.mancc = b.mancc;
        String tenanh = TenAnhLabel.getText();
        if(tenanh.equals("No file selected"))
            sp.hinhanh = "";
        else{
            sp.hinhanh = tenanh.substring(0, tenanh.lastIndexOf(".jpg"));
            //Copy image to this project folder
            try{
                String projectpath = System.getProperty("user.dir");
                projectpath = projectpath + "\\src\\images\\"+jfc.getSelectedFile().getName();
                projectpath = projectpath.replace("\\", File.separator);
                Path src = Paths.get(jfc.getSelectedFile().getAbsolutePath());
                Path dest = Paths.get(projectpath);
                Files.copy(src, dest, REPLACE_EXISTING);
            }catch(IOException e){
                e.printStackTrace();
            }
        }
        sanphamBUS.Them(sp);
        JOptionPane.showMessageDialog(null, "Thêm sản phẩm thành công","Success",JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
    }//GEN-LAST:event_ThemButtonActionPerformed

    private void MaSPTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaSPTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaSPTextActionPerformed

    private void TenTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TenTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TenTextActionPerformed

    private void GiaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GiaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GiaTextActionPerformed

    private void SoLuongTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoLuongTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SoLuongTextActionPerformed

    private void HinhAnhButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HinhAnhButtonActionPerformed
        jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        FileNameExtensionFilter filter = new FileNameExtensionFilter("IMAGE FILES (.jpg)", "jpg", "JPG Images");
        jfc.setFileFilter(filter);
        jfc.setAcceptAllFileFilterUsed(false);
        int returnValue = jfc.showOpenDialog(null);
        if(returnValue == JFileChooser.APPROVE_OPTION)
        {
            File selectedFile = jfc.getSelectedFile();
            String imgname = selectedFile.getName();
            TenAnhLabel.setText(imgname);
            imageurl = selectedFile.getAbsolutePath();
            ImageIcon image = new ImageIcon(imageurl);
            //If image is not available
            if (image != null) {
            } else {
                image = new ImageIcon(this.getClass().getResource("/images/No_image_available.png"));
            }
            //Resize image
            Image newimage = image.getImage();
            Image resize = newimage.getScaledInstance(150, 158, java.awt.Image.SCALE_SMOOTH);
            image = new ImageIcon(resize);
            //Show image
            HinhAnhLabel.setIcon(image);
        }

    }//GEN-LAST:event_HinhAnhButtonActionPerformed

    private void NCCComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NCCComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NCCComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemSanPham().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GIaLabel;
    private javax.swing.JTextField GiaText;
    private javax.swing.JButton HinhAnhButton;
    private javax.swing.JLabel HinhAnhLabel;
    private javax.swing.JButton HuyButton;
    private javax.swing.JComboBox<String> LoaiComboBox;
    private javax.swing.JLabel LoaiLabel;
    private javax.swing.JLabel MaSPLabel;
    private javax.swing.JTextField MaSPText;
    private javax.swing.JComboBox<String> NCCComboBox;
    private javax.swing.JLabel NCCLabel;
    private javax.swing.JLabel SoLuongLabel;
    private javax.swing.JTextField SoLuongText;
    private javax.swing.JLabel TenAnhLabel;
    private javax.swing.JLabel TenLabel;
    private javax.swing.JTextField TenText;
    private javax.swing.JButton ThemButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
