/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlydtdd;

import DTO.hoadonnhapDTO;
import BUS.hoadonnhapBUS;
import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class ThongKeChi extends javax.swing.JInternalFrame {

    /**
     * Creates new form QuanLyThongTinSanPham
     */
    String [] columns = new String [] {"Mã hóa đơn","Ngày nhập","Tổng tiền"};
    DefaultTableModel modeltable = new DefaultTableModel(null, columns);
    
    void HienThiDS(ArrayList dshd) 
    {
        modeltable.getDataVector().removeAllElements();
        for (int i = 0; i < dshd.size(); i++) {
            hoadonnhapDTO a = (hoadonnhapDTO) dshd.get(i);
            modeltable.insertRow(i, new Object[]{a.mahdn, a.ngaynhap, a.tongtien});
        }
        jTable1.setModel(modeltable);
    }
    
    public ThongKeChi()
    {
        initComponents();
        ButtonGroup rg = new ButtonGroup();
        rg.add(NgayRadioButton);
        rg.add(ThangRadioButton);
        rg.add(NamRadioButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NgayXuatLabel = new javax.swing.JLabel();
        NgayText = new javax.swing.JTextField();
        ThangText = new javax.swing.JTextField();
        NamText = new javax.swing.JTextField();
        TongTienLabel = new javax.swing.JLabel();
        TongTienText = new javax.swing.JTextField();
        LoaiLabel = new javax.swing.JLabel();
        ThongKeButton = new javax.swing.JButton();
        NgayRadioButton = new javax.swing.JRadioButton();
        ThangRadioButton = new javax.swing.JRadioButton();
        NamRadioButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        NgayXuatLabel.setText("Thời gian:");

        NgayText.setEnabled(false);

        ThangText.setEnabled(false);
        ThangText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThangTextActionPerformed(evt);
            }
        });

        NamText.setEnabled(false);

        TongTienLabel.setText("Tổng tiền:");

        TongTienText.setEditable(false);
        TongTienText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TongTienTextActionPerformed(evt);
            }
        });

        LoaiLabel.setText("Thống kê theo:");

        ThongKeButton.setText("Thống kê");
        ThongKeButton.setEnabled(false);
        ThongKeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThongKeButtonActionPerformed(evt);
            }
        });

        NgayRadioButton.setText("Ngày");
        NgayRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NgayRadioButtonActionPerformed(evt);
            }
        });

        ThangRadioButton.setText("Tháng");
        ThangRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThangRadioButtonActionPerformed(evt);
            }
        });

        NamRadioButton.setText("Năm");
        NamRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamRadioButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("/");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel2.setText("/");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LoaiLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NgayRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ThangRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NamRadioButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NgayXuatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TongTienLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(NgayText, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ThangText, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NamText, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TongTienText))
                        .addGap(18, 18, 18)
                        .addComponent(ThongKeButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoaiLabel)
                    .addComponent(NgayRadioButton)
                    .addComponent(ThangRadioButton)
                    .addComponent(NamRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NgayXuatLabel)
                            .addComponent(NgayText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ThangText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NamText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ThongKeButton)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TongTienLabel)
                    .addComponent(TongTienText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {NgayXuatLabel, ThangText, TongTienLabel, TongTienText});

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã hóa đơn", "Ngày nhập", "Tổng tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TongTienTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TongTienTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TongTienTextActionPerformed

    private void ThangTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThangTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ThangTextActionPerformed

    private void ThongKeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThongKeButtonActionPerformed
        String thoigian = "";
        if(NgayRadioButton.isSelected())
        {
            thoigian = NgayText.getText() + "/" + ThangText.getText() + "/" + NamText.getText();
            ArrayList dshd = hoadonnhapBUS.TimKiemTheoNgay(thoigian);
            HienThiDS(dshd);
        }
        else if(ThangRadioButton.isSelected())
        {
            thoigian = ThangText.getText() + "/" + NamText.getText();
            ArrayList dshd = hoadonnhapBUS.TimKiemTheoThang(thoigian);
            HienThiDS(dshd);
        }
        else if(NamRadioButton.isSelected())
        {
            thoigian = NamText.getText();
            ArrayList dshd = hoadonnhapBUS.TimKiemTheoThang(thoigian);
            HienThiDS(dshd);
        }
        float tongtien = 0;
        TongTienText.enable(true);
        for(int i = 0; i < modeltable.getRowCount(); i++)
        {
            tongtien += Float.parseFloat(String.valueOf(modeltable.getValueAt(i,2)));
        }
        TongTienText.setText(String.valueOf(tongtien));
    }//GEN-LAST:event_ThongKeButtonActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void NgayRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NgayRadioButtonActionPerformed
        NgayText.enable(true);
        ThangText.enable(true);
        NamText.enable(true);
        NgayText.setText("");
        ThangText.setText("");
        NamText.setText("");
        ThongKeButton.setEnabled(true);
    }//GEN-LAST:event_NgayRadioButtonActionPerformed

    private void ThangRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThangRadioButtonActionPerformed
        NgayText.enable(false);
        ThangText.enable(true);
        NamText.enable(true);
        NgayText.setText("");
        ThangText.setText("");
        NamText.setText("");
        ThongKeButton.setEnabled(true);
    }//GEN-LAST:event_ThangRadioButtonActionPerformed

    private void NamRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamRadioButtonActionPerformed
        NgayText.enable(false);
        ThangText.enable(false);
        NamText.enable(true);
        NgayText.setText("");
        ThangText.setText("");
        NamText.setText("");
        ThongKeButton.setEnabled(true);
    }//GEN-LAST:event_NamRadioButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LoaiLabel;
    private javax.swing.JRadioButton NamRadioButton;
    private javax.swing.JTextField NamText;
    private javax.swing.JRadioButton NgayRadioButton;
    private javax.swing.JTextField NgayText;
    private javax.swing.JLabel NgayXuatLabel;
    private javax.swing.JRadioButton ThangRadioButton;
    private javax.swing.JTextField ThangText;
    private javax.swing.JButton ThongKeButton;
    private javax.swing.JLabel TongTienLabel;
    private javax.swing.JTextField TongTienText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
